package ru.sbt.mipt.oop.events.typedefs;

public enum EventType {
    LIGHT_ON, LIGHT_OFF, DOOR_OPEN, DOOR_CLOSED, HOME_LIGHTS_OFF, HOME_LIGHTS_ON, ROOM_LIGHTS_OFF, ROOM_LIGHTS_ON, GET_HALLDOOR,
    ALARM_ACTIVATE, ALARM_DEACTIVATE, ALARM_WARNING, GET_ALARM_STATE;
}
